Update to build cleanly
jasoncoon/esp32-fastled-webserver pull request #21
Opened 2019-08-22 16:16 UTC by henrygab

Fixes #20
Fixes #10

### Use `webserver.h` instead of `ESP8266WebServer.h`

Makes this build without dependencies.

### Fix `Missing field initializers` warnings.

In fields.h, while FieldList is an array, the array elements are each a POD struct of type Field, which has no non-default constructor. Therefore, according to the specification:
> The effects of default initialization are:
> …
> otherwise, nothing is done: the objects with automatic storage duration (and their subobjects) are initialized to indeterminate values.

### Fix `Comparisons always false due to limited range of data type` warning

Simply put, the long result from string.toInt() was placed into an uint8_t, prior to clamping the value. This change stores the conversion result in a long to perform the clamping prior to storing the value in the uint8_t field.

### Fix `warning: extra tokens at end of #include directive`

Remove semi-colons from #include lines

### Fix `error: multi-line comment [-Werror=comment]`

Ensure the last character of a comment line is not a backslash character.

### Fix `warning: 'typedef' was ignored in this declaration`

Move the name `Field` to follow the struct definition.

2019-08-22 16:23 UTC, jasoncoon requested changes

2019-08-22 16:23 UTC, jasoncoon commented on fields.h
> +  currentPaletteIndex = tmp;
Thanks for this pull request!  Shouldn't this actually clamp to `[0.. paletteCount-1]` (as noted in the comment( instead of `[1.. paletteCount+1]`?

2019-08-22 16:54 UTC, henrygab commented
@jasoncoon Fixed.  Thanks for review and catching that!

2020-03-05 03:27 UTC, jasoncoon approved these changes
Sorry for the massive delay, thank you!

2020-03-05 03:27 UTC, merged